[package]
name = "dive"
version = "0.1.7"
edition = "2021"
default-run = "dive"

[features]
embedded_image = []

[dependencies]
anstream = { version = "0.6.18", default-features = false, features = ["auto"] }
anyhow = "1.0.93"
base64 = "0.22.1"
clap = { version = "4.5.21", features = ["derive", "env"] }
dirs = "5.0"
env_logger = "0.11.5"
exitcode = "1.1.2"
fd-lock = "4.0.2"
indicatif = "0.17.9"
ioctl-sys = "0.8.0"
itertools = "0.13.0"
libc = "0.2.164"
liblzma = { version = "0.3.5", features = ["static"] }
log = "0.4.22"
owo-colors = "4.1.0"
procfs = { version= "0.17.0" }
regex = "1.11.1"
rustix = { version = "0.38.40", features = ["process", "thread", "mount", "fs", "runtime"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
tar = "0.4.43"
tempfile = "3.14.0"
ureq = { version = "2.10.1", default-features = false, features = ["tls", "native-certs", "gzip", "json"] }
which = "7.0.0"

[[bin]]
name = "dive"

[[bin]]
name = "build-img"

[[bin]]
name = "pkg"
